name: Deploy Application

on:
  push:
    branches:
      - main

jobs:

  deploy-all:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      #################################################
      # AWS LOGIN
      #################################################

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      #################################################
      # TERRAFORM
      #################################################

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply -auto-approve

      #################################################
      # GET EC2 IP
      #################################################

      - name: Get EC2 Public IP
        working-directory: terraform
        run: |
          echo "EC2_IP=$(terraform output -raw public_ip)" >> $GITHUB_ENV

      #################################################
      # DOCKER BUILD
      #################################################

      - name: DockerHub Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image
        run: |
          docker build -t glacierknight/hello-world-devops:latest ./app

      - name: Push Docker Image
        run: |
          docker push glacierknight/hello-world-devops:latest

      #################################################
      # SSH KEY
      #################################################

      - name: Create SSH Key
        run: |
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > private_key.pem
          chmod 400 private_key.pem

      #################################################
      # WAIT FOR EC2
      #################################################

      - name: Wait for EC2 Initialization
        run: sleep 120

      #################################################
      # COPY K8S FILES
      #################################################

      - name: Copy Kubernetes Files
        run: |
          scp -o StrictHostKeyChecking=no \
          -i private_key.pem \
          k8s/deployment.yaml \
          k8s/service.yaml \
          ubuntu@$EC2_IP:/home/ubuntu/

      #################################################
      # DEPLOY TO K3S
      #################################################

      - name: Deploy to K3s
        run: |
          ssh -o StrictHostKeyChecking=no \
          -i private_key.pem \
          ubuntu@$EC2_IP << EOF

            kubectl apply -f /home/ubuntu/deployment.yaml

            kubectl apply -f /home/ubuntu/service.yaml

            kubectl get pods

            kubectl get svc

          EOF
